### ISSUE TITLE
The play button on the main widget panel doesn't work

### ISSUE THREAD

**Issue by BugHunterPhilosopher** [mika-nt28/Jeedom-Plex#2]
Meaning it doesn't trigger the playing of the media item currently displayed in the widget, nor of the currently selected media item on the Plex client.

**Comment by AlienQueen** [comment]
The only way to trigger a media play is to navigate to the right element thanks to the arrows of the right widget panel, and to issue a "Select" command.

That's not very convenient, IMHO : you have to use the computer (Jeedom client) to choose a media on your phone (which is the Plex client), because if you tap on it with your finger, it doesn't select it, it launches it. Then only can you use your phone as an alarm clock or whatever.
